% This code belongs to the HDM05 mocap database which can be obtained
% from the website http://www.mpi-inf.mpg.de/resources/HDM05 .
%
% If you use and publish results based on this code and data, please
% cite the following technical report:
%
%   @techreport{MuellerRCEKW07_HDM05-Docu,
%     author = {Meinard M{\"u}ller and Tido R{\"o}der and Michael Clausen and Bernd Eberhardt and Bj{\"o}rn Kr{\"u}ger and Andreas Weber},
%     title = {Documentation: Mocap Database {HDM05}},
%     institution = {Universit{\"a}t Bonn},
%     number = {CG-2007-2},
%     year = {2007}
%   }
%
%
% THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
% KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
% IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
% PARTICULAR PURPOSE.

function map = constructNameMap(skel)

% format:
% standard joint name, DOF ID, trajectory ID

switch skel.fileType
    case 'TOM.ASF'
map = {'root',1,1;... 
       'lhip',3,25;...      %25 sacroiliac_@_l_hip 
       'lknee',4,26;...     %26 l_hip_@_l_knee 
       'lankle',5,27;...    %27 l_knee_@_l_ankle 
       'ltoes',0,29;...     %29 l_metatarsal_@_l_forefoot_tip
       'rhip',8,31;...      %31sacroiliac_@_r_hip    
       'rknee',9,32;...     %32r_hip_@_r_knee    
       'rankle',10,33;...   %33r_knee_@_r_ankle 
       'rtoes',0,35;...     %35r_metatarsal_@_r_forefoot_tip 
       'belly',13,4;...     %4vl1_@_vt10     
       'chest',14,5;...     %5vt10_@_vt6 
       'neck',15,6;...      %6vt6_@_vt1
       'head',17,7;...      %7vt1_@_skullbase 
       'headtop',0,8;...   %8skullbase_@_skull_tip
       'lclavicle',18,6;... 
       'lshoulder',19,13;...%13l_acromioclavicular_@_l_shoulder 
       'lelbow',20,14;...   %14l_shoulder_@_l_elbow
       'lwrist',22,15;...   %15l_elbow_@_l_wrist   
       'lfingers',0,16;...  %16l_wrist_@_l_wrist_tip
       'rclavicle',25,6;... 
       'rshoulder',26,19;...%19r_acromioclavicular_@_r_shoulder
       'relbow',27,20;...   %20r_shoulder_@_r_elbow
       'rwrist',29,21;...   %21r_elbow_@_r_wrist
       'rfingers',0,22};    %22r_wrist_@_r_wrist_tip 
    case 'ASF'
map = {'root',1,1;...
       'lhip',3,2;...
       'lknee',4,3;...
       'lankle',5,4;...
       'ltoes',0,6;...
       'rhip',8,7;...
       'rknee',9,8;...
       'rankle',10,9;...
       'rtoes',0,11;...
       'belly',13,12;...
       'chest',14,13;...
       'neck',15,14;...
       'head',17,16;...
       'headtop',0,17;...
       'lclavicle',18,14;...
       'lshoulder',19,18;...
       'lelbow',20,19;...
       'lwrist',22,21;...
       'lfingers',0,23;...
       'rclavicle',25,14;...
       'rshoulder',26,25;...
       'relbow',27,26;...
       'rwrist',29,28;...
       'rfingers',0,30};   
   case 'BVH'
map = {'root',1,1;...
       'lhip',19,18;...
       'lknee',20,19;...
       'lankle',21,20;...
       'ltoes',0,21;...
       'rhip',23,22;...
       'rknee',24,23;...
       'rankle',25,24;...
       'rtoes',0,25;...
       'belly',3,2;...
       'chest',17,3;...
       'neck',15,14;...
       'head',16,15;...
       'headtop',0,16;...
       'lclavicle',5,4;...
       'lshoulder',6,5;...
       'lelbow',7,6;...
       'lwrist',8,7;...
       'lfingers',0,8;...
       'rclavicle',10,9;...
       'rshoulder',11,10;...
       'relbow',12,11;...
       'rwrist',13,12;...
       'rfingers',0,13};
    case 'MPII'
map = {'root',0,1;...
       'lhip',0,2;...
       'lknee',0,3;...
       'lankle',0,4;...
       'ltoes',0,5;...
       'rhip',0,6;...
       'rknee',0,7;...
       'rankle',0,8;...
       'rtoes',0,9;...
       'belly',0,10;...
       'chest',0,11;...
       'neck',0,12;...
       'head',0,13;...
       'headtop',0,14;...
       'lclavicle',0,15;...
       'lshoulder',0,16;...
       'lelbow',0,17;...
       'lwrist',0,18;...
       'lfingers',0,19;...
       'lhand',0,19;...
       'rclavicle',0,20;...
       'rshoulder',0,21;...
       'relbow',0,22;...
       'rwrist',0,23;...
       'rfingers',0,24;...
       'rhand',0,24};   
end